"""Generate the self-describing record embedded in every FW2 RAM app."""
import argparse
import struct
import zlib

MAGIC = b"FW2AINFO"
SIZE = 216
BODY = "<8s H B B H H 32s 128s 32s I"


def fixed(value, size, label):
    raw = value.encode("ascii", "strict")
    if len(raw) >= size:
        raise SystemExit("%s is too long (maximum %d ASCII bytes)" %
                         (label, size - 1))
    return raw + bytes(size - len(raw))


def build_record(version, name, description, build="", build_ts=0):
    if not 0 <= version <= 999:
        raise ValueError("VERSION must be in 000-999")
    body = struct.pack(BODY, MAGIC, 1, 0, 0, version, 0,
                       fixed(name, 32, "NAME"),
                       fixed(description, 128, "DESCRIPTION"),
                       fixed(build, 32, "BUILD"), build_ts)
    assert len(body) == SIZE - 4
    return body + struct.pack("<I", zlib.crc32(body) & 0xffffffff)


def emit(record):
    rows = ["    " + " ".join("0x%02X," % b for b in record[i:i + 12])
            for i in range(0, len(record), 12)]
    return ("/* Generated by tools/gen_uf2_info.py. */\n"
            "#include \"common/uf2_info.h\"\n\n"
            "__attribute__((used))\n"
            "const unsigned char fw2app_uf2_info[%d] = {\n%s\n};\n"
            "_Static_assert(sizeof(fw2app_uf2_info) == "
            "sizeof(fw2app_uf2_info_t), \"UF2 info layout mismatch\");\n"
            % (len(record), "\n".join(rows)))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    parser.add_argument("--version", type=int, required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--description", required=True)
    parser.add_argument("--build", default="")
    parser.add_argument("--build-ts", type=int, default=0)
    args = parser.parse_args()
    if not 0 <= args.version <= 999:
        raise SystemExit("VERSION must be in 000-999")
    if not args.description:
        raise SystemExit("DESCRIPTION must not be empty")
    with open(args.out, "w", newline="\n") as output:
        output.write(emit(build_record(args.version, args.name,
                                       args.description, args.build,
                                       args.build_ts)))


if __name__ == "__main__":
    main()
