name: Build Flipper App
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: sudo apt update && sudo apt install -y cmake gcc-arm-none-eabi ninja-build python3 git
      - run: |
          git clone --branch 2.3.0 --depth 1 https://github.com/raspberrypi/pico-sdk.git ~/pico-sdk
          cd ~/pico-sdk && git submodule update --init
          echo "PICO_SDK_PATH=$HOME/pico-sdk" >> $GITHUB_ENV
      - run: |
          export PICO_SDK_PATH=$HOME/pico-sdk
          python3 tools/fw.py build FlipperZero
      - uses: actions/upload-artifact@v4
        with:
          name: FlipperZero-App
          path: build/apps/flipper_zero/*.uf2
